#based on https://raw.github.com/leviwilson/android-travis-ci-example/master/.travis.yml
language: java
branches:
  except:
    - ariadnelocation
before_install:
  # install ia32-libs, see http://rkistner.github.io/android/2013/02/05/android-builds-on-travis-ci/
  - sudo apt-get update -qq
  - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch; fi
  # download the latest android sdk and unzip
  - wget http://dl.google.com/android/android-sdk_r22.2.1-linux.tgz
  - tar -zxf android-sdk_r22.2.1-linux.tgz
  - export ANDROID_HOME=`pwd`/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  # only update the sdk for the tools and platform-tools (1,2) and whatever api level
  # you are building for android (run "android list sdk" to get the full list.  4 = 4.3 or API level 18
  - echo "y" | android update sdk --filter 1,2,4 --no-ui --force
script: mvn test cobertura:cobertura coveralls:cobertura -B
